export const USER_SUBMITTED_AN_EMPTY_VALUE = 'USER_SUBMITTED_AN_EMPTY_VALUE';
export const USER_SUBMITTED = 'USER_SUBMITTED';
export const USER_LUCKY_SUBMITTED = 'USER_LUCKY_SUBMITTED';

export const FETCH_LOADING = 'FETCH_LOADING';
export const FETCH_SET = 'FETCH_SET';
export const FETCH_SET_LUCK = 'FETCH_SET_LUCK';
export const FETCH_ERROR = 'FETCH_ERROR';

